'use strict';
export default {
  ca: 'Catalan',
  es: 'Spanish',
  en: 'English',
  description: 'David Gómez Nin: Software Engineer specialized in Web Development',
  homeH2: 'David Gómez Nin',
  homeSubtitle: 'Software Engineer specialized in Web Development',
  skills: 'Skills',
  skillsFrontend: 'Frontend',
  skillsFrontendDesc: 'Web Development work area in which I have more competencies and experience. I have worked with several libraries and resources like BackboneJS, SASS, Gulp, LeafletJS and I can learn to work with new ones.',
  skillsBackend: 'Backend',
  skillsBackendDesc: 'My experience in Backend is based on the FullStack jobs I have carried out and on the support to Backend team in my last experience before working as a Freelance. When it comes to making websites without great particularities on the server side, I choose Wordpress as CMS.',
  skillsDesign: 'Design',
  skillsDesignDesc: 'My knowledge in this area is self-taught and responds to the interest of having some control of all phases of web development and especially to be able to build HTML/CSS templates based on Adobe Illustrator and Photoshop documents.',
  portfolio: 'Portfolio',
  work1Title: 'Interactive Map: The military industry in Spain',
  work1Desc: 'Project done as Freelance for the Delàs Center. It\'s a Web frontend application for reading information about the main arms companies in the territory of Spain. It uses the Leaflet map management JS library and its extension to group bookmarks.',
  work1Uri: 'http://www.centredelas.org/en/database/military-industry/interactive-map-the-military-industry-in-spain',
  work2Title: 'My Green Energy Planet (in Spanish)',
  work2Desc: 'A project done by OneBigRobot for WWF consisting on a turn-based strategy web game which seeks to raise awareness about possible measures to reduce emission of polluting gases. My participation was focused on the programming and layout of the frontend and part of the backend programming in PHP.',
  work3Title: 'Campanya Roba Neta (in Catalan)',
  work3Desc: 'Project done as Freelance for Setem. This is a website that is mainly used as a blog. It runs on the CMS Wordpress and my work was developing the template, doing its layout and programming its backend part.',
  work4Title: 'Worldwide Armed Banks Database',
  work4Desc: 'Project done as Freelance for the Delàs Center. It\'s a Web frontend application to show the financial relationship between banks and armament companies at international scale. The application uses liraries to generate graphics based on canvas technology.',
  work4Uri: 'http://www.centredelas.org/bancaarmada/en/',
  portfolioGitHub: 'GitHub',
  portfolioGitHubText: 'Visit my GitHub',
  curriculum: 'Curriculum',
  curriculumStudy: 'University',
  curriculumWork: 'Work',
  exp1Title: 'Computer Engineering',
  exp1Desc: 'Universitat Politècnica de Catalunya BarcelonaTech',
  exp1Time: 'September 2005 - December 2011',
  exp2Title: 'LSI Departament from the UPC',
  exp2Desc: 'Software Developer JS',
  exp2Time: 'July 2008 - September 2009',
  exp3Title: 'Genomvisió S.L.',
  exp3Desc: 'Software Developer JS',
  exp3Time: 'January 2010 - February 2012',
  exp4Title: 'OneBigRobot S.L.',
  exp4Desc: 'Developer Frontend/Backend + HTML/CSS Templates',
  exp4Time: 'May 2012 - August 2014',
  exp5Title: 'AdMan Media',
  exp5Desc: 'Software Developer JS',
  exp5Time: 'May 2015 - January 2017',
  exp6Title: 'Freelance',
  exp6Desc: 'Software Developer JS + Developer Frontend/Backend + HTML/CSS Templates',
  exp6Time: 'February 2017 - September 2018',
  curriculumStack: 'StackOverflow',
  curriculumPDF: 'Download PDF',
  curriculumStackLabel: 'Visit my Stack Overflow profile',
  curriculumPDFLabel: 'Download PDF',
  contact: 'Contact',
  mailImage: 'Send me an email',
  contactText: 'If you have any question, doubt or offer, contact me:'
};
