'use strict';
export default {
  description: 'David Gómez Nin: Programador especializado en Desarrollo Web',
  homeH2: 'David Gómez Nin',
  homeSubtitle: 'Programador especializado en Desarrollo Web',
  skills: 'Habilidades',
  skillsFrontend: 'Frontend',
  skillsFrontendDesc: 'Area de trabajo del Desarrollo Web en la que tengo más competencias y experiencia. He trabajado con varias librerías y recursos como BackboneJS, SASS, Gulp, LeafletJS y no me supone un problema trabajar con nuevas.',
  skillsBackend: 'Backend',
  skillsBackendDesc: 'Mi experiencia en el Backend se fundamenta en los trabajos FullStack que he llevado a cabo y trabajos de soporte al equipo de Backend en mi última experienca antes de trabajar como Freelance. Cuando se trata de hacer webs sin grandes particularidades en el lado servidor escojo Wordpress como CMS.',
  skillsDesign: 'Diseño',
  skillsDesignDesc: 'Mis conocimientos en este area son autodidáctas y responden al interés de tener cierto control de todas las fases del desarrollo web y sobretodo a poder maquetat efectivamente partiendo de documentos de Adobe Illustrator y Photoshop.',
  portfolio: 'Portfolio',
  work1Title: 'Mapa Interactivo: La Industria Militar en España',
  work1Desc: 'Proyecto hecho como Freelance para el Centre Delàs. Aplicación web frontend para obtener información de las principales empresas armamentísticas en el territorio de España. Usa el software de gestión de mapas Leaflet y de su extensión para agrupar marcadores.',
  work1Uri: 'http://www.centredelas.org/es/base-de-datos/industria-militar/mapa-interactivo-la-industria-militar-en-espana',
  work2Title: 'My Green Energy Planet',
  work2Desc: 'Proyecto de OneBigRobot para WWF que consiste en un juego de estrategia por turnos con el cual se busca concienciar sobre posibles medidas para reducir la emissión de gases contaminantes. Mi participación se centró en la programación y maquetación del frontend y parte de la programación backend en PHP.',
  work3Title: 'Campanya Roba Neta',
  work3Desc: 'Proyecto hecho como Freelance para Setem. Se trata de un sitio web que cumple sobretodo la función de blog. Funciona sobre el CMS Wordpress y el trabajo consistió en desarrollar la plantilla, maquetándola y programando su parte backend.',
  work4Title: 'Base de Datos Internacional de Banca Armada',
  work4Desc: 'Proyecto hecho como Freelance para el Centre Delàs. Aplicación web frontend para mostrar la relación de financiamiento entre bancos y empresas armamentísticas a escala internacional. La aplicación usa librerías de generación de gráficos que funcionan sobre canvas.',
  work4Uri: 'http://www.centredelas.org/bancaarmada/es/',
  portfolioGitHub: 'GitHub',
  portfolioGitHubText: 'Visita mi GitHub',
  curriculum: 'Currículum',
  curriculumStudy: 'Universidad',
  curriculumWork: 'Trabajo',
  exp1Title: 'Ingeniería Informática',
  exp1Desc: 'Universidad Politécnica de Catalunya BarcelonaTech',
  exp1Time: 'Septiembre 2005 - Diciembre 2011',
  exp2Title: 'Departamento de LSI de la UPC',
  exp2Desc: 'Desarrollador de Software JS',
  exp2Time: 'Julio 2008 - Septiembre 2009',
  exp3Title: 'Genomvisió S.L.',
  exp3Desc: 'Desarrollador de Software JS',
  exp3Time: 'Enero 2010 - Febrero 2012',
  exp4Title: 'OneBigRobot S.L.',
  exp4Desc: 'Programador Frontend/Backend + Maquetación',
  exp4Time: 'Mayo 2012 - Agosto 2014',
  exp5Title: 'AdMan Media',
  exp5Desc: 'Desarrollador de Software JS',
  exp5Time: 'Mayo 2015 - Enero 2017',
  exp6Title: 'Freelance',
  exp6Desc: 'Desarrollador de Software JS + Programador Frontend/Backend + Maquetación',
  exp6Time: 'Febrero 2017 - Septiembre 2018',
  curriculumStack: 'StackOverflow',
  curriculumPDF: 'Descarga PDF',
  curriculumStackLabel: 'Visita el perfil de Stack Overflow',
  curriculumPDFLabel: 'Descarga en PDF',
  contact: 'Contacto',
  mailImage: 'Envíame un correo',
  contactText: 'Si tienes alguna pregunta, duda u oferta, no dudes en ponerte en contacto:'
};
